### ISSUE TITLE
is it possible to run the same generation but for people with no hair?

### ISSUE THREAD

**Issue by johndpope** [SelfishGene/SFHQ-dataset#1]
would be useful to do stuff like import into training for this
https://github.com/oneThousand1000/HairMapper

**Comment by SelfishGene** [comment]
Could you clarify what you mean by running the same generation for people with no hair?

There are quite a few generated faces without hair in the dataset, it's possible to find them by querying the CLIP features for "bald hair", have a look here: https://www.kaggle.com/code/selfishgene/explore-synthetic-faces-hq-sfhq-dataset
