### ISSUE TITLE
What is the status of part3?

### ISSUE THREAD

**Issue by rex-yue-wu** [SelfishGene/SFHQ-dataset#3]
Really excited to see it for quite a long time, and now it is Nov.

**Comment by SelfishGene** [comment]
Yeah, sorry for the delay, my current best estimate is that I will be able to finalize it sometime toward the middle/end of December, not earlier. But the good news is that I will likely also add a part 4 and potentially also a part 5 (each with around ~100K images) shortly after that, which will increase the dataset diversity further.

**Comment by rex-yue-wu** [comment]
Thanks for the update.

**Comment by SelfishGene** [comment]
Parts 3 & 4 have been updated and are now available to download from kaggle. 
These parts contain a total of ~243,000 new images. see more details in the readme file
